### ISSUE TITLE
example has error

### ISSUE THREAD

**Issue by studywolf** [project-rig/nengo_spinnaker#118]
indent should be removed after line 36, i believe! fix: 

``` python
# Import modules
import csv
import numpy as np
import nengo
import nengo_spinnaker

# Import classes
from nengo.processes import WhiteNoise
from nengo_spinnaker.utils import profiling

# Parameters to profile
dimensions = 1
ensemble_size = 200

model = nengo.Network()
with model:
    # Create standard communication channel network with white noise input
    inp = nengo.Node(WhiteNoise(), label="inp")
    inp_p = nengo.Probe(inp)

    pre = nengo.Ensemble(ensemble_size, dimensions=dimensions, label="pre")
    pre_p = nengo.Probe(pre, synapse=0.01)
    nengo.Connection(inp, pre)

    post = nengo.Ensemble(ensemble_size, dimensions=dimensions, label="post")
    posts_p = nengo.Probe(post, synapse = 0.01)
    nengo.Connection(pre, post,
                     function=lambda x: np.random.random(dimensions))

    # Setup SpiNNaker-specific options to supply white noise from on
    # chip and profile the ensemble at the start of the channel
    nengo_spinnaker.add_spinnaker_params(model.config)
    model.config[inp].function_of_time = True
    model.config[pre].profile = True

# Create a SpiNNaker simulator and run model
sim = nengo_spinnaker.Simulator(model)
with sim:
    sim.run(10.0)

# Read profiler data
profiler_data = sim.profiler_data[pre]

# Open CSV file and create writer
with open("profile_communication_channel.csv", "wb") as csv_file:
    csv_writer = csv.writer(csv_file)

    # Write header row for CSV with extra columns
    # for number of neurons and dimensions
    profiling.write_csv_header(profiler_data, csv_writer,
                               ["Num neurons", "Dimensions"])

    # Write a row from the profiler data dollo
    profiling.write_csv_row(profiler_data, csv_writer,
                            [ensemble_size, dimensions])
```

**Comment by neworderofjamie** [comment]
@studywolf, can you verify this fix works for you?

**Comment by studywolf** [comment]
I'm just heading in to the office, should be able to verify in about 2-3 hours!

**Comment by bjkomer** [comment]
When I run this I get an error in the `write_csv_row` function

```
Traceback (most recent call last):
  File "test_example.py", line 55, in <module>
    [ensemble_size, dimensions])
  File "/home/bjkomer/.local/lib/python2.7/site-packages/nengo_spinnaker-0.2.5-py2.7.egg/nengo_spinnaker/utils/profiling.py", line 54, in write_csv_row
    mean_times = [np.average(t[1]) for t in profiling_data.values()]
KeyError: 1
```

**Comment by neworderofjamie** [comment]
Did you checked nengo spinnaker out from git (if so which branch are you on) or get it via pip?

**Comment by bjkomer** [comment]
I checked it out from git, on the master branch.
