### ISSUE TITLE
attributerror

### ISSUE THREAD

**Issue by piewchee** [project-rig/nengo_spinnaker#168]
Hi 
I am using a Spin5 local board.
Python:2.7
Numpy: 1.13.3
nengo: 2.6
nengo_spinnaker:0.4.0
on Ubuntu:14

when I try to "python learn_associations.py"
The example is unable to run with the following error.
File "/usr/local/lib/python2.7/dist-packages/nengo_spinnaker/builder/ensemble.py", line 166, in build_lif
max_rates = ensemble.sample(ens.max_rates, ens.n_neurons, rng=rng)
AttributError:'module' object has no attribute 'sample'

May I know what is wrong?

Rgds
Del

**Comment by tcstewar** [comment]
Hmm, that shouldn't be happening....  Could you post the full error message?

**Comment by piewchee** [comment]
Thanks for the quick reply. Here it is:
Intercept: 0.695247434695
Traceback (most recent call last):
  File "learn_assoc.py", line 83, in <module>
    sim = nengo_spinnaker.Simulator(model)
  File "/usr/local/lib/python2.7/dist-packages/nengo_spinnaker/simulator.py", line 114, in __init__
    self.model.build(network, **builder_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/nengo_spinnaker/builder/builder.py", line 205, in build
    self._build_network(network)
  File "/usr/local/lib/python2.7/dist-packages/nengo_spinnaker/builder/builder.py", line 221, in _build_network
    self.make_object(obj)
  File "/usr/local/lib/python2.7/dist-packages/nengo_spinnaker/builder/builder.py", line 235, in make_object
    self._builders[type(obj)](self, obj)
  File "/usr/local/lib/python2.7/dist-packages/nengo_spinnaker/builder/ensemble.py", line 146, in build_ensemble
    ensemble_builders[type(ens.neuron_type)](model, ens)
  File "/usr/local/lib/python2.7/dist-packages/nengo_spinnaker/builder/ensemble.py", line 166, in build_lif
    max_rates = ensemble.sample(ens.max_rates, ens.n_neurons, rng=rng)
AttributeError: 'module' object has no attribute 'sample'

**Comment by tcstewar** [comment]
Argh, that's my fault.  The most recent version of nengo_spinnaker fixes this bug, but it's not set up to auto-install that recent version yet.  

One solution is to go back to an older version of nengo by doing `pip install nengo==2.2.0`.  However, a better solution is to install the latest version of nengo_spinnaker.

Do this by downloading the latest version here: https://github.com/project-rig/nengo_spinnaker/archive/master.zip then unzip the folder, go into the directory that has setup.py in it, and do `pip install -e .`

That should fix things!  Let me know if that works or if anything isn't clear....

**Comment by piewchee** [comment]
Hi,
Excellent! It works now.

Thanks and Regards
Del
