### ISSUE TITLE
Probe on output node throws exception

### ISSUE THREAD

**Issue by pabogdan** [project-rig/nengo_spinnaker#45]
The following piece of code is a minimal  example of a bug arising when using nengo_gui with SpiNNaker. It works fine both on Nengo and SpiNNaker when you don't have a graph (probe) to follow the value of the "output" node. When adding the probe, Nengo runs, but Nengo_SpiNNaker doesn't, giving the stack trace at the bottom.

``` python
import nengo
import numpy as np

model = nengo.Network("Buggy - output not working")


with model:
    input = nengo.Node(lambda t: np.sin(t))
    middle = nengo.Ensemble(50, 1)
    output = nengo.Node(size_in=1)
    nengo.Connection(input, middle)
    nengo.Connection(middle, output)
```

<pre> <code>
Exception in thread Thread-126:
Traceback (most recent call last):
  File "c:\Python27\lib\threading.py", line 810, in __bootstrap_inner
    self.run()
  File "c:\Python27\lib\threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "C:\nengo_gui\nengo_gui\viz.py", line 129, in runner
    self.build()
  File "C:\nengo_gui\nengo_gui\viz.py", line 98, in build
    self.sim = backend.Simulator(self.model)
  File "C:\nengo_spinnaker\nengo_spinnaker\simulator.py", line 111, in __init__
    self.netlist = self.model.make_netlist(self.max_steps or 0)
  File "C:\nengo_spinnaker\nengo_spinnaker\builder\builder.py", line 328, in make_netlist
    self, *args, **kwargs
  File "C:\nengo_spinnaker\nengo_spinnaker\operators\filter.py", line 83, in make_vertices
    SDRAM: regions.utils.sizeof_regions(self.regions, slice(None)),
  File "C:\nengo_spinnaker\nengo_spinnaker\regions\utils.py", line 43, in sizeof_regions
    size = sum(r.sizeof_padded(vertex_slice) for r in regions if r is not None)
  File "C:\nengo_spinnaker\nengo_spinnaker\regions\utils.py", line 43, in <genexpr>
    size = sum(r.sizeof_padded(vertex_slice) for r in regions if r is not None)
  File "C:\nengo_spinnaker\nengo_spinnaker\regions\region.py", line 12, in sizeof_padded
    n_bytes = self.sizeof(vertex_slice)
  File "C:\nengo_spinnaker\nengo_spinnaker\regions\matrix.py", line 83, in sizeof
    self.matrix[self.expanded_slice(vertex_slice)].nbytes)
IndexError: too many indices for array
</code> </pre>

**Comment by mundya** [comment]
Cannot reproduce. Can you try again?

What versions of things are you using?

**Comment by mundya** [comment]
I believe this has now been fixed.
