### ISSUE TITLE
Running sim in virtualenv

### ISSUE THREAD

**Issue by pabogdan** [project-rig/nengo_spinnaker#61]
Running any sort of simulation while in a virtualenv seems to throw the error at the bottom of the page.

``` python
import nengo

model = nengo.Network()
with model:
    stim = nengo.Node([0])
    a = nengo.Ensemble(n_neurons=50, dimensions=1)
    nengo.Connection(stim, a)
```

nengo_gui with debug output shows it crashes at building the model

``` bash
INFO:nengo_spinnaker.utils.machine_control:Checking that SpiNNaker board '192.168.240.1' is booted
INFO:nengo_spinnaker.utils.machine_control:Board is booted with SC&MP/SpiNNaker v1.33
DEBUG:nengo_spinnaker.simulator:Building model
```

Actual error

``` bash
Traceback (most recent call last):
  File "/home/PhD15/bogdanp/nengo_gui/nengo_gui/page.py", line 423, in build
    self.sim = backend.Simulator(self.model)
  File "/home/PhD15/bogdanp/AlanProject/venv/lib/python2.7/site-packages/nengo_spinnaker-0.2.4-py2.7.egg/nengo_spinnaker/simulator.py", line 94, in __init__
  File "/home/PhD15/bogdanp/AlanProject/venv/lib/python2.7/site-packages/nengo_spinnaker-0.2.4-py2.7.egg/nengo_spinnaker/builder/builder.py", line 212, in build
  File "/home/PhD15/bogdanp/AlanProject/venv/lib/python2.7/site-packages/nengo_spinnaker-0.2.4-py2.7.egg/nengo_spinnaker/builder/builder.py", line 232, in _build_network
  File "/home/PhD15/bogdanp/AlanProject/venv/lib/python2.7/site-packages/nengo_spinnaker-0.2.4-py2.7.egg/nengo_spinnaker/builder/builder.py", line 252, in make_connection
  File "/home/PhD15/bogdanp/AlanProject/venv/lib/python2.7/site-packages/nengo_spinnaker-0.2.4-py2.7.egg/nengo_spinnaker/builder/ensemble.py", line 168, in build_from_ensemble_connection
TypeError: cached_solver() takes at least 6 arguments (3 given)
```

**Comment by mundya** [comment]
This is waiting on resolution of #60 - Nengo changed, that's the problem.

**Comment by tcstewar** [comment]
Yup...  I'm just finishing off some testing of #60 so this should be resolved shortly....

**Comment by mundya** [comment]
Thanks :)

**Comment by mundya** [comment]
#60 was merged, so this issue fixed.
